export const HTTP_STATUS_LIST: { code: number; name: string; description: string }[] = [
  { code: 100, name: "Continue", description: "Client should continue with request" },
  { code: 101, name: "Switching Protocols", description: "Server is switching protocols" },
  { code: 200, name: "OK", description: "Request succeeded" },
  { code: 201, name: "Created", description: "Resource created" },
  { code: 204, name: "No Content", description: "Success, no body" },
  { code: 301, name: "Moved Permanently", description: "Resource moved permanently" },
  { code: 302, name: "Found", description: "Temporary redirect" },
  { code: 304, name: "Not Modified", description: "Use cached version" },
  { code: 400, name: "Bad Request", description: "Invalid request" },
  { code: 401, name: "Unauthorized", description: "Authentication required" },
  { code: 403, name: "Forbidden", description: "Access denied" },
  { code: 404, name: "Not Found", description: "Resource not found" },
  { code: 405, name: "Method Not Allowed", description: "HTTP method not allowed" },
  { code: 408, name: "Request Timeout", description: "Client took too long" },
  { code: 409, name: "Conflict", description: "Request conflicts with state" },
  { code: 422, name: "Unprocessable Entity", description: "Validation failed" },
  { code: 429, name: "Too Many Requests", description: "Rate limited" },
  { code: 500, name: "Internal Server Error", description: "Server error" },
  { code: 502, name: "Bad Gateway", description: "Invalid response from upstream" },
  { code: 503, name: "Service Unavailable", description: "Server temporarily unavailable" },
];
